version: '3.7'

services:
  backend:
    build: backend/.
    command: python /usr/src/3papp/src/run.py
    ports:
      - 5000:5000
  db:
    image: postgres:10.12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Poklm9222
      - POSTGRES_DB=postgres

  frontend:
    build: frontend/.
    command: ng serve --host 0.0.0.0
    ports:
      -4200:4200